"""Initial migration

Revision ID: 3a73609bfa63
Revises: 8fd5488e8a33
Create Date: 2025-08-15 01:20:10.442493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a73609bfa63'
down_revision = '8fd5488e8a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_code_expires_at', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('verification_requests_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('verification_requests_locked_until', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_requests_locked_until')
        batch_op.drop_column('verification_requests_count')
        batch_op.drop_column('email_code_expires_at')

    # ⚠️ ملاحظة: جدول spatial_ref_sys خاص بـ PostGIS ولا يجب حذفه أو إنشاؤه هنا
    # إذا احتجت فعلاً إنشاؤه، خلي Alembic يتعامل معه بملف مستقل
    # ### end Alembic commands ###