"""Initial migration

Revision ID: 3b4f2ce37868
Revises: aa593daef8fa
Create Date: 2025-08-16 22:22:55.852986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b4f2ce37868'
down_revision = 'aa593daef8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'email_verification_requests_count',
            sa.Integer(),
            nullable=False,
            server_default="0"
        ))
        batch_op.add_column(sa.Column(
            'email_verification_requests_locked_until',
            sa.TIMESTAMP(timezone=True),
            nullable=True
        ))
        batch_op.add_column(sa.Column(
            'phone_verification_requests_count',
            sa.Integer(),
            nullable=False,
            server_default="0"
        ))
        batch_op.add_column(sa.Column(
            'phone_verification_requests_locked_until',
            sa.TIMESTAMP(timezone=True),
            nullable=True
        ))
        batch_op.alter_column(
            'profile_image_url',
            existing_type=sa.VARCHAR(length=255),
            nullable=True,
            existing_server_default=sa.text(
                "'https://placehold.co/400x400/EFEFEF/AAAAAA?text=User'::character varying"
            )
        )
        batch_op.drop_column('verification_requests_count')
        batch_op.drop_column('verification_requests_locked_until')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'verification_requests_locked_until',
            postgresql.TIMESTAMP(timezone=True),
            nullable=True
        ))
        batch_op.add_column(sa.Column(
            'verification_requests_count',
            sa.INTEGER(),
            nullable=False,
            server_default=sa.text('0')
        ))
        batch_op.alter_column(
            'profile_image_url',
            existing_type=sa.VARCHAR(length=255),
            nullable=False,
            existing_server_default=sa.text(
                "'https://placehold.co/400x400/EFEFEF/AAAAAA?text=User'::character varying"
            )
        )
        batch_op.drop_column('phone_verification_requests_locked_until')
        batch_op.drop_column('phone_verification_requests_count')
        batch_op.drop_column('email_verification_requests_locked_until')
        batch_op.drop_column('email_verification_requests_count')
    # ### end Alembic commands ###