"""Initial migration

Revision ID: 8fd5488e8a33
Revises: 
Create Date: 2025-08-14 17:53:09.980131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '8fd5488e8a33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_addresses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('address_line', sa.Text(), nullable=True),
        sa.Column('location', geoalchemy2.types.Geometry(
            geometry_type='POINT',
            srid=4326,
            dimension=2,
            from_text='ST_GeomFromEWKT',
            name='geometry',
            nullable=False
        ), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # إنشاء index على العمود location إذا لم يكن موجودًا
    conn = op.get_bind()
    exists = conn.execute(
        text("SELECT 1 FROM pg_indexes WHERE indexname = 'idx_user_addresses_location'")
    ).fetchone()

    if not exists:
        with op.batch_alter_table('user_addresses', schema=None) as batch_op:
            batch_op.create_index(
                'idx_user_addresses_location',
                ['location'],
                unique=False,
                postgresql_using='gist'
            )

    # تم إزالة محاولة حذف جدول spatial_ref_sys
    # ### end Alembic commands ###


def downgrade():
    # حذف الـ index والجدول user_addresses فقط
    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.drop_index('idx_user_addresses_location', postgresql_using='gist')

    op.drop_table('user_addresses')
    # ### end Alembic commands ###